local base = require "nvchad.configs.mason"

return vim.tbl_deep_extend("force", base, {
  pkgs = {
    "lua-language-server",
    "stylua",
    "css-lsp",
    "html-lsp",
    "typescript-language-server",
    "deno",
    "prettier",
    "json-lsp",
    "eslint-lsp",
    "buf",
    "protols",
    "clang-format",
    "rust-analyzer",
    "selene",
    "sqlfluff",
    "haskell-language-server",
    "pyright",
    "mypy",
    "zls",
    "ruff-lsp",
    "shellcheck",
    "vacuum",
    "actionlint",
    "buf",
    "cpplint",
    "hadolint",
    "markdownlint",
    "marksman",
    "revive",
    "stylelint",
    "cmake-language-server",
    "yaml-language-server",
    "gopls",
    "angular-language-server",
    "typos-lsp",
    "dockerfile-language-server",
    "docker-compose-language-service",
    "taplo",
    "vtls",
  },
})
