
[bell]
animation = "EaseOutExpo"
duration = 0

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font Mono"

[font.normal]
family = "FiraCode Nerd Font Mono"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
args = ["new-session", "-A", "-s", "main"]
program = "/opt/homebrew/bin/tmux"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Maximized"

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 10
y = 10

[general]

live_config_reload = true
import = ["~/.config/alacritty/themes/themes/catppuccin.toml"]

[terminal]
